# Generated by Django 2.2.3 on 2019-08-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(blank=True, max_length=60)),
                ('facility_type', models.CharField(blank=True, max_length=30)),
                ('city_name', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('zip_code', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
